import type { Translate, PreferenceController, AccountStatusController } from './client-types.js';
import type { QuotaForecast } from './forecast-types.js';
export { CHANNEL, unwrap } from './rpc-contract.js';
export declare const NS = "settings.codexSubscription";
export declare const SUPPORT_ISSUE_URL = "https://github.com/Pascapone/dsh-codex-subscription/issues/new?template=install-problem.yml";
export declare const QUICK_QUOTA_REFRESH_EVENT = "dsh-codex-subscription:refresh-quick-quota";
export declare const QUICK_QUOTA_REFRESH_MS = 60000;
export declare const accountStatusErrorText: (error: {
    code?: string;
} | undefined, t: Translate) => string;
export declare const fill: (text: string, values: Readonly<Record<string, unknown>>) => string;
export declare const maskEmail: (value: unknown) => string;
export declare const hours: (seconds: number) => number;
export declare const percent: (value: unknown) => string;
export declare const isApproximateWindow: (seconds: number, expected: number) => boolean;
export declare const windowLabel: (seconds: number, t: Translate) => string;
export declare const validDate: (value: unknown) => Date | undefined;
export declare const usePreferenceSnapshot: (preference: PreferenceController) => Readonly<{
    connectionMode: string;
    compactionMode: string;
    codexBasePrompt: boolean;
    subagentBackend: string;
    subagentBackendAvailable: boolean;
    subagentRuntimeInstalled: boolean;
    quickQuotaMode: import("./settings-types.js").QuickQuotaMode;
    searchProvider: import("./settings-types.js").SearchProvider;
    speedMode: import("./settings-types.js").SpeedMode;
    sessionSpeedModes: {
        [x: string]: unknown;
    };
    outputVerbosity: import("./settings-types.js").OutputVerbosity;
    contextMode: import("./settings-types.js").ContextMode;
    customContextWindow: number;
    customContextWindows: {
        [x: string]: number;
    };
    contextModels: import("./preference-types.js").ContextModelDescriptor[];
    verbosityModels: string[];
    fastModels: string[] | undefined;
    catalogStatus: unknown;
    modelsLoading: boolean;
    modelError: boolean;
    writable: boolean;
    saving: boolean;
    error: boolean;
    imageGeneration: boolean;
    imageShortcut: boolean;
    imageEditing: boolean;
    imageViewer: boolean;
    imageAnnotations: boolean;
    imageSketch: boolean;
    imageSketchAgent: boolean;
    imageSketchAgentPreview: boolean;
    imageModel: import("./settings-types.js").ImageModel;
    imageQuality: import("./settings-types.js").ImageQuality;
    quotaShortThreshold: number;
    quotaLongThreshold: number;
    customContextModels: Record<string, number>;
    searchMode: import("./settings-types.js").SearchMode;
    searchDomains: string[];
    quotaAlerts: import("./settings-types.js").QuotaAlertMode;
    transcriptionEnabled: boolean;
    status: "ready" | "loading" | "unavailable";
}>;
export declare const useAccountStatusSnapshot: (accountStatus: AccountStatusController) => ReturnType<AccountStatusController["getSnapshot"]>;
export declare const notifyQuickQuota: () => boolean;
export declare const formatRunway: (seconds: number | undefined, t: Translate) => string | undefined;
export declare const formatQuotaForecast: (forecast: QuotaForecast | {
    status: "idle";
} | null | undefined, t: Translate) => string | undefined;
