import type { ContextModel, ContextModelGroup, SearchProvider, OutputVerbosity, SpeedMode, ContextMode, QuickQuotaMode } from './settings-types.js';
export declare const SETTINGS_NAMESPACE = "codex-subscription";
export declare const QUICK_QUOTA_MODE_FIELD = "quickQuotaMode";
export declare const LEGACY_QUICK_QUOTA_FIELD = "quickQuotaVisible";
export declare const QUICK_QUOTA_MODE_OFF = "off";
export declare const QUICK_QUOTA_MODE_PERCENT = "percent";
export declare const QUICK_QUOTA_MODE_BAR = "bar";
export declare const QUICK_QUOTA_MODE_FORECAST = "forecast";
export declare const DEFAULT_QUICK_QUOTA_MODE = "off";
export declare const SEARCH_PROVIDER_FIELD = "searchProvider";
export declare const SEARCH_PROVIDER_AUTO = "auto";
export declare const SEARCH_PROVIDER_DSH = "dsh";
export declare const SEARCH_PROVIDER_CODEX = "codex";
export declare const DEFAULT_SEARCH_PROVIDER = "auto";
export declare const SPEED_MODE_FIELD = "speedMode";
export declare const SESSION_SPEED_MODES_FIELD = "sessionSpeedModes";
export declare const SPEED_MODE_STANDARD = "standard";
export declare const SPEED_MODE_FAST = "fast";
export declare const DEFAULT_SPEED_MODE = "standard";
export declare const OUTPUT_VERBOSITY_FIELD = "outputVerbosity";
export declare const OUTPUT_VERBOSITY_DEFAULT = "default";
export declare const OUTPUT_VERBOSITY_LOW = "low";
export declare const OUTPUT_VERBOSITY_MEDIUM = "medium";
export declare const OUTPUT_VERBOSITY_HIGH = "high";
export declare const DEFAULT_OUTPUT_VERBOSITY = "default";
export declare const CONTEXT_MODE_FIELD = "contextMode";
export declare const CONTEXT_MODE_STANDARD = "standard";
export declare const CONTEXT_MODE_EXTENDED = "extended";
export declare const CONTEXT_MODE_CUSTOM = "custom";
export declare const DEFAULT_CONTEXT_MODE = "standard";
export declare const CUSTOM_CONTEXT_WINDOW_FIELD = "customContextWindow";
export declare const DEFAULT_CUSTOM_CONTEXT_WINDOW = 272000;
export declare const MIN_CUSTOM_CONTEXT_WINDOW = 128000;
export declare const MAX_CUSTOM_CONTEXT_WINDOW = 1000000;
export declare const CUSTOM_CONTEXT_MODEL_FIELDS: Readonly<{
    'gpt-5.4': "customContextGpt54";
    'gpt-5.4-mini': "customContextGpt54Mini";
    'gpt-5.5': "customContextGpt55";
    'gpt-5.6': "customContextGpt56";
    'gpt-6-astra': "customContextGpt6Astra";
}>;
export declare const CUSTOM_CONTEXT_MODEL_CAPS: Readonly<{
    'gpt-5.4': 1000000;
    'gpt-5.4-mini': 400000;
    'gpt-5.5': 1000000;
    'gpt-5.6': 1000000;
    'gpt-6-astra': 872000;
}>;
export declare const CUSTOM_CONTEXT_MODEL_DEFAULTS: Readonly<{
    'gpt-5.4': 272000;
    'gpt-5.4-mini': 272000;
    'gpt-5.5': 272000;
    'gpt-5.6': 272000;
    'gpt-6-astra': 272000;
}>;
export declare const normalizeSearchProvider: (value: unknown) => SearchProvider;
export declare const normalizeOutputVerbosity: (value: unknown) => OutputVerbosity;
export declare const normalizeSpeedMode: (value: unknown) => SpeedMode;
export declare const normalizeContextMode: (value: unknown) => ContextMode;
export declare const normalizeCustomContextWindow: (value: unknown, maximum?: number) => number;
export declare const formatContextWindow: (value: number) => string;
export declare const parseContextWindow: (value: unknown) => number;
export declare const customContextModelKey: (modelId: string | undefined) => string | undefined;
export declare function modelContextMaximum(model: ContextModel | undefined): number;
export declare function clampModelContext(value: unknown, maximum: number, fallback?: number): number;
export declare function contextModelGroups(models: readonly (ContextModel | undefined)[] | undefined): ContextModelGroup[];
export declare const normalizeQuickQuotaMode: (value: unknown, legacyVisible?: unknown) => QuickQuotaMode;
export declare const supportsCodexFastMode: (modelId: unknown) => modelId is string;
